version: '3.8'

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        USE_TAR: "false"
    hostname: web
    networks:
      - gateway-net
    ports:
      - "8000:80"
    environment:
      SERVICE_HOST: "web"
    env_file: .env
    volumes:
      - ./web/image/default.conf:/etc/nginx/sites-enabled/default.conf
    working_dir: /var/www/html

  nginx:
    build: ./services/nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "443:443"
    environment:
      GATEWAY_HOST: ${GATEWAY_HOST:-gateway-svc}
      GATEWAY_PORT: ${GATEWAY_PORT:-8080}
    networks:
      - gateway-net
      - internal-net

  gateway-svc:
    container_name: gateway-svc
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    hostname: gateway-svc
    networks:
      - internal-net
    expose:
      - "8080"
    env_file: .env
    volumes:
      - ./services/gateway/image/default.conf:/etc/nginx/sites-enabled/default.conf
    working_dir: /var/www/html
    depends_on:
      - consul

  auth-svc:
    container_name: auth-svc
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    hostname: auth-svc
    networks:
      - internal-net
    expose:
      - "8080"
    env_file:
      - .env
      - ./db/auth/.env
    depends_on:
      - auth-svc-db
      - consul
    volumes:
      - ./services/auth/image/default.conf:/etc/nginx/sites-enabled/default.conf
    working_dir: /var/www/html

  auth-svc-db:
    container_name: auth-svc-db
    hostname: auth-svc-db
    networks:
      - internal-net
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    #    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./db/auth/mysql-data:/var/lib/mysql

  product-svc:
    container_name: product-svc
    build:
      context: ./services/product
      dockerfile: Dockerfile
    hostname: product-svc
    networks:
      - internal-net
    expose:
      - "8080"
    env_file:
      - .env
      - ./db/product/.env
    depends_on:
      - product-svc-db
      - consul
    volumes:
      - ./services/product/image/default.conf:/etc/nginx/sites-enabled/default.conf
    working_dir: /var/www/html

  product-svc-db:
    container_name: product-svc-db
    hostname: product-svc-db
    networks:
      - internal-net
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    #    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./db/product/mysql-data:/var/lib/mysql

  consul:
    image: consul:1.15.4
    container_name: consul
    hostname: consul-svc
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    networks:
      - internal-net

networks:
  gateway-net:
  internal-net:


